Add docker-registry cephfs-storage.

diff --git a/docker-registry/base/credential-rotator-cronjob.yaml b/docker-registry/base/credential-rotator-cronjob.yaml
--- a/docker-registry/base/credential-rotator-cronjob.yaml
+++ b/docker-registry/base/credential-rotator-cronjob.yaml
@@ -1,9 +1,11 @@
 apiVersion: batch/v1beta1
 kind: CronJob
 metadata:
-  name: registry-credential-rotator
+  name: registry-credential-rotator-cron
 spec:
-  schedule: "0 12 * * 1" # every monday at 12:00
+  # Initially run every minute to create credentials.
+  # Every run sets the schedule to a longer interval.
+  schedule: "*/1 * * * *"
   jobTemplate:
     spec:
       template:
@@ -20,10 +22,17 @@ spec:
                 MIN_TIME_AGO="$(expr $MIN_TIME_AGO - $MIN_ROTATION_INTERVAL_MINUTES '*' 60)" || (echo Invalid MIN_ROTATION_INTERVAL_MINUTES env var >&2; false)
                 apk add --update --no-cache apache2-utils curl
                 TOKEN="$(cat /run/secrets/kubernetes.io/serviceaccount/token)"
-                NAMESPACE="$(cat /run/secrets/kubernetes.io/serviceaccount/namespace)"
                 APISERVER=https://kubernetes.default.svc
                 ln -s /run/secrets/kubernetes.io/serviceaccount/ca.crt /usr/local/share/ca-certificates/ca.cert
                 update-ca-certificates
+
+                # Patch cronjob schedule to run once per day
+                ERR="$(curl -fsS -XPATCH \
+                  -H "Authorization: Bearer $TOKEN" \
+                  -H 'Content-Type: application/strategic-merge-patch+json' \
+                  "$APISERVER/apis/batch/v1beta1/namespaces/$NAMESPACE/cronjobs/$CRON_NAME" \
+                  -d '{"spec":{"schedule": "0 0 1 * *"}}' 2>&1)" \
+                  || (echo -n "Cannot patch CronJob $CRON_NAME schedule: $ERR" >&2; sleep 15; false)
 
                 # Check if the secret exists and hasn't been updated after the given threshold
                 HTPASSWD_SECRET_NAME=${DEPLOYMENT_NAME}-htpasswd
@@ -46,7 +55,7 @@ spec:
                   SEC="$(cat -)"
                   OUT="$(echo "$SEC" | curl -fsS -XPUT -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' "$APISERVER/api/v1/namespaces/$NAMESPACE/secrets/$1" -d @-)" \
                     || OUT="$(echo "$SEC" | curl -fsS -XPOST -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' "$APISERVER/api/v1/namespaces/$NAMESPACE/secrets" -d @-)" \
-                    || (echo "ERROR: failed to write secret '$1'. $OUT" >&2; false)
+                    || (echo -n "Cannot write secret '$1'. $OUT" >&2; sleep 15; false)
                 }
                 base64enc() {
                   echo -n "$1" | base64 | xargs | sed -e 's/ //g'
@@ -111,6 +120,12 @@ spec:
                   writeSecret ${DEPLOYMENT_NAME}-push-credentials
                 echo secrets successfully written
             env:
+            - name: CRON_NAME
+              value: $(CRON_NAME)
+            - name: NAMESPACE
+              valueFrom:
+                fieldRef:
+                  fieldPath: metadata.namespace
             - name: SERVICE_NAMESPACE
               value: $(SERVICE_NAMESPACE)
             - name: SERVICE_NAME
