Improved docker-registry kustomization.
Organized in base and overlays.
Namespace undefined - leaving it to the user.
Enabled name prefix/suffixes.
Made updateable (using Deployments + CronJob).

PROBLEM REMAINING: test deployment is unstable.

diff --git a/docker-registry/base/registry-clusterip-injector-daemonset.yaml b/docker-registry/base/registry-clusterip-injector-daemonset.yaml
--- a/docker-registry/base/registry-clusterip-injector-daemonset.yaml
+++ b/docker-registry/base/registry-clusterip-injector-daemonset.yaml
@@ -4,7 +4,6 @@ apiVersion: extensions/v1beta1
 kind: DaemonSet
 metadata:
   name: registry-clusterip-injector-daemonset
-  namespace: docker-registry
 spec:
   updateStrategy:
     type: RollingUpdate
@@ -22,21 +21,19 @@ spec:
         - |
             set -eo pipefail
             [ "$SERVICE_NAME" ] || (echo SERVICE_NAME env var is empty >&2; false)
-            addHostsEntry() {
-              SVC_NAME="$1"
-              FQN="$2"
-              SVC_IP="$(getent hosts "$SVC_NAME" | awk '{ print $1 }')" || (echo "Cannot resolve IP of service '$SVC_NAME'" >&2; false)
-              FQN_ESCAPED="$(echo "$FQN" | sed 's/\./\\./g')"
-              HOSTS_FILE=/host/etc/hosts
-              HOSTS="$(sed -Ee "s/\s+$FQN_ESCAPED(\s+|\$)/ /g" -Ee '/^[^\s]+\s*$/d' -e "\$a$SVC_IP $FQN" $HOSTS_FILE)"
-              echo "$HOSTS" > ${HOSTS_FILE}.tmp
-              mv ${HOSTS_FILE}.tmp $HOSTS_FILE || echo "$HOSTS" > $HOSTS_FILE # workaround for containerized k8s where /etc/hosts is mounted
-              rm -f ${HOSTS_FILE}.tmp
-              echo "Node's /etc/hosts updated with $FQN pointing to $SVC_IP"
-            }
-            SERVICE_NAME="${SERVICE_NAME}.${SERVICE_NAMESPACE}.svc"
-            addHostsEntry "$SERVICE_NAME" "$COMMON_NAME"
-            addHostsEntry "$SERVICE_NAME" "$SERVICE_NAME"
+            SVC_NAME="${SERVICE_NAME}.${SERVICE_NAMESPACE}.svc"
+            NAMES="$SVC_NAME"
+            if [ "$SVC_NAME" != "$COMMON_NAME" ]; then
+              NAMES="$COMMON_NAME $NAMES"
+            fi
+            SVC_IP="$(getent hosts "$SVC_NAME" | awk '{ print $1 }')" || (echo "Cannot resolve IP of service '$SVC_NAME'" >&2; false)
+            SVC_NAME_ESCAPED="$(echo "$SVC_NAME" | sed 's/\./\\./g')"
+            HOSTS_FILE=/host/etc/hosts
+            grep -Ev "\s+$SVC_NAME_ESCAPED(\s+|\$)" $HOSTS_FILE > ${HOSTS_FILE}.tmp
+            echo "$SVC_IP $NAMES" >> ${HOSTS_FILE}.tmp
+            mv ${HOSTS_FILE}.tmp $HOSTS_FILE || cat ${HOSTS_FILE}.tmp > $HOSTS_FILE # workaround for containerized k8s where /etc/hosts is mounted
+            rm -f ${HOSTS_FILE}.tmp
+            echo "Node's /etc/hosts updated: $SVC_IP $NAMES"
             while true; do sleep 86400; done
         env:
         - name: SERVICE_NAMESPACE
